{{- if .Values.webui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "get_iplayer.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "get_iplayer.name" $ }}
  template:
    metadata:
      labels:
        app: {{ template "get_iplayer.name" $ }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "get_iplayer.name" $ }}
        command: ["/app/get_iplayer.cgi", "-g", "/app/get_iplayer.sh", "-b", "http://{{ .Values.ingress.host }}/{{ .Values.ingress.path }}/", "--listen", "0.0.0.0", "--port", "1935"]
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        ports:
          - name: {{ include "get_iplayer.name" . }}
            containerPort: 1935
        # Mount the NFS volume in the container
        volumeMounts:
{{- range $key, $val := .Values.content }}
        - name: {{ $key }}
          mountPath: {{ $val.mount }}
{{- end }}
      # Add the NFS volume to the Pod
      volumes:
{{- range $key, $val := .Values.content }}
      - name: {{ $key }}
      {{- if $val.nfs }}
        # Set the NFS server and path to the share
        nfs:
          server: {{ $val.nfs.server }}
          path: {{ $val.nfs.path }}
          readOnly: false
      {{- end }}
{{- end }}
      affinity:
        {{- if .Values.affinity }}
{{ toYaml .Values.affinity | trim | indent 8 }}
        {{- end }}
{{- end }}