{{- if .Values.webui.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "get_iplayer.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  - http:
      paths:
      - path: /{{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "get_iplayer.name" . }}
            port:
              number: 80
{{- end }}